# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elmseeds
description: > # this means to ignore newlines until "baseurl:"
  Short screencasts to teach you the Elm programming language.
  Each video tutorial walks through a library, tool, or language feature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elmseeds.thaterikperson.com" # the base hostname & protocol for your site
twitter_username: thaterikperson
github_username:  thaterikperson
permalink: /:title
paginate: 20
paginate_path: "/archive/:num/"

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
